#ifndef DEFINE_H
#define DEFINE_H

#define BIRD_SIZE 45
#define BIRD_DIVISOR 1.5
#define BIRD_UPTIME 300
#define BIRD_UPBOUND -174
#define BIRD_UPDISTANCE 50
#define ROAD_HEIGHT 64
#define ROAD_YVALUE 384
#define ROAD_TIME 2990
#define BARRIER_TIME 3000
#define GAME_LOOP_TIME 50
#define WIDTH 384
#define HEIGHT 448

#endif // DEFINE_H
