######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 20 13:01:58 2010
######################################################################

TEMPLATE = app
TARGET = QDesktopWindowDocker
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui widgets

# Input
HEADERS += QDesktopWindowDocker.h QMainWindowExample.h
SOURCES += main.cpp QDesktopWindowDocker.cpp QMainWindowExample.cpp
