######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:00:47 2008
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets core-private widgets-private

TEMPLATE = app
TARGET = cursor
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cursor.h
SOURCES += cursor.cpp main.cpp
RESOURCES += cursor.qrc
TRANSLATIONS += cursor_zh.ts
