#ifndef DEFINE_H
#define DEFINE_H

#define ACCOUNTLENGTH 20
#define PASSWORDLENGTH  20
#define ANIMATIONTIME 500
#define WIDTH 600
#define HEIGHT 400
#define MAX 12
#define BUTTONWIDTH 80
#define BUTTONHEIGHT 20
#define ICONWIDTH 160
#define ICONHEIGHT  213
#define ACCOUNTLENGTH 12
#define PASSWORDLENGTH 15

#endif // DEFINE_H
