#ifndef HEAD_H
#define HEAD_H

#include <QWidget>
#include <QDialog>
#include <QMainWindow>
#include <QLabel>
#include <QDebug>
#include <QFile>
#include <QPushButton>
#include <QLineEdit>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QTextStream>
#include <QString>
#include <QMessageBox>
#include <QPalette>
#include <QPixmap>
#include <QToolButton>
#include <QIcon>
#include <QPropertyAnimation>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QStringList>
#include <QHeaderView>
#include <QTableView>
#include <QList>
#include <fstream>
#include <string.h>
#include <QTableWidgetItem>
#include <QSpinBox>
#include <QRegExp>
#include <QRegExpValidator>
#include <QRadioButton>
#include <QButtonGroup>
#include <QFile>
#include "define.h"
#include "struct.h"

#endif // HEAD_H
