######################################################################
# Automatically generated by qmake (2.01a) Mi. Okt 5 19:27:34 2011
######################################################################

TEMPLATE = app
TARGET = QtSpline
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets core gui

# Input
HEADERS += gui.h scene.h SpBezier.h SpHook.h SpNode.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp scene.cpp SpBezier.cpp SpHook.cpp SpNode.cpp
