######################################################################
# Automatically generated by qmake (2.01a) Di. Okt 4 23:24:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core widgets gui

# Input
HEADERS += gui.h scene.h SpHook.h SpNode.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp scene.cpp SpHook.cpp SpNode.cpp
